listen_address: ":9090"
rest_address: ":8080"
data_dir: "/var/lib/gimpel-master"

tls:
  cert_file: "/var/lib/gimpel-certs/master.crt"
  key_file: "/var/lib/gimpel-certs/master.key"

ca:
  cert_file: "/var/lib/gimpel-certs/ca.crt"
  key_file: "/var/lib/gimpel-certs/ca.key"
  auto_generate: false

registry:
  stale_timeout: 5m
  cleanup_interval: 1m

sandbox:
  nodes:
    - "sandbox:5000"

module_store:
  data_dir: "/var/lib/gimpel-master/modules"
